### PR TITLE
gui and save file

### PR DESCRIPTION
**Pull request by ozheng1993**

### CODE REVIEW

**Comment by WinPooh32** [comment]
Hello guys,  I am glad to see you working with engine. But I don't understand what are you doing. Also you try update old version of engine. Latest repo you can find here https://github.com/boldtempleGaming/Engine

If you have problems you can ask me, I'll help you.

**Comment by ozheng1993** [comment]
My bad. I clicked pull request by mistake. We made a map editor/creator that is now finished. But it only makes maps of a fixed size. We did not understand your demo cause it was not using tiles. It was using entity. If you like what we did you can pull our level editor. It was an assignment for a class using c++. You edit maps through the console. We didn't create a gui with c++ cause we have not learned yet. If you want, we can make a better gui using Java to output and edit maps. :) I'll have my teammate resend the pull request for you to see. Ignore all the changes we made to the engine. Only look at  the Map_Demo directory.

Thank you
Ou Zheng

**Comment by WinPooh32** [comment]
I like your work. And it will be good if you make gui using engine. I can teach you, if you want.

**Comment by ozheng1993** [comment]
Yes, our team would love too! But this will have to be done over the summer. We are in mid-finals week right now. 

Thank you
Ou Zheng

**Comment by WinPooh32** [comment]
If your team are interested in it, I can make some helpful examples for you and explain how it works.

**Comment by ozheng1993** [comment]
That would help a lot. Thanks!

Thank you
Ou Zheng

**Comment by WinPooh32** [comment]
You should say what examples you need.

**Comment by ozheng1993** [comment]
We need to see an example of your tiling class being used in the engine demo. Also, we need to see a smaller/clearer example of a cmake file. We've only been using regular makefile's.

Ps: my name is Christian Smithroat. I've been emailing you from Ou's phone. His English is not very clear and I'm getting a lil lazy from using his account, so email me at cjsmithro@gmail.com please. :)

Thank you
Ou Zheng (but really Chris)

**Pull request closed without merging**
